project_souda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('remind/', include('remind.urls')),
]

remind/urls.py
from django.urls import path
from . import views

app_name = 'remind'

urlpatterns = [
    path('', views.IndexView.as_view(),name='index'), #/remind
    path('add/',views.AddView.as_view(),name='add'), #/diary/add
    path('update/<int:pk>',views.UpdateView.as_view(),name='update'),# diary/update/1
    path('delete/<int:pk>/',views.DeleteView.as_view(),name='delete'), #diary/delete/1
    path('detail/<int:pk>/',views.DetailView.as_view(),name='detail') #diary/detail/1
]

remind/models.py
from django.db import models
from django.utils import timezone #djangoでは、datetime.nowのかわりに、timezzone.nowで現在時刻を取得する


class Task(models.Model):
    subject = models.CharField('項目',max_length=255)
    contents = models.TextField('内容',max_length=255)
    date = models.DateField('日付',default=timezone.now)
    name = models.CharField('担当者',max_length=30)

    def __str__(self):
        return self.subject

remind/forms.py
from django import forms
from .models import Task


class TaskCreateForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__' #('title','text','date)

remind/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import TaskCreateForm
from .models import Task


class IndexView(generic.ListView):
    queryset = Task.objects.order_by("-date").reverse()
    paginate_by = 50


class AddView(generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy('remind:index')


class UpdateView(generic.UpdateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy('remind:index')


class DeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('remind:index')


class DetailView(generic.DetailView):
    model = Task

remind/templates/remind/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>リマインドアプリケーション</title>  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
    <div class="container">
      <nav class="nav">
        <a class="nav-link" href="{% url 'remind:index' %}">一覧</a>
        <a class="nav-link" href="{% url 'remind:add' %}" target="_blank">追加</a>
      </nav>
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

remind/templates/remind/task_confirm_delete.html
{% extends 'remind/base.html' %}

{% block content %}
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{ task.subject}}</td>
        </tr>
        <tr>
            <th>内容</th>
            <td>{{ task.contents}}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ task.date }}</td>
        </tr>
        <tr>
            <th>担当者</th>
            <td>{{ task.name }}</td>
        </tr>
    </table>
    <p>こちらのデータを削除します。</p>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

remind/templates/remind/task_detail.html
{% extends 'remind/base.html' %}

{% block content %}
<table class="table">
    <tr>
        <th>タイトル</th>
        <td>{{ task.subject}}</td>
    </tr>
    <tr>
        <th>内容</th>
        <td>{{ task.contents}}</td>
    </tr>
    <tr>
        <th>日付</th>
        <td>{{ task.date }}</td>
    </tr>
    <tr>
        <th>担当者</th>
        <td>{{ task.name }}</td>
    </tr>
</table>
{% endblock %}

remind/templates/remind/task_form.html
{% extends 'remind/base.html' %}

{% block content %}
<p>{{task.title}}</p>
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>タイトル</th>
            <td>{{ form.subject}}</td>
        </tr>
        <tr>
            <th>内容</th>
            <td>{{ form.contents}}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
        <tr>
            <th>担当者</th>
            <td>{{ form.name }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

remind/templates/remind/task_list.html
{% extends 'remind/base.html' %}

{% block content %}
<h1>タスク一覧</h1>
<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>内容</th>
            <th>日付</th>
            <th>担当者</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        {% for task in task_list %}
        <tr>
            <td>{{ task.subject}}</td>
            <td>{{ task.contents}}</td>
            <td>{{ task.date}}</td>
            <td>{{ task.name}}</td>
            <td><a href="{% url 'remind:update' task.pk %}" target="_blank">更新</a></td>
            <td><a href="{% url 'remind:delete' task.pk %}" target="_blank">削除</a></td>
        </tr>
        {% endfor %}
    </tbody>

</table>

{% endblock %}